name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Checkout submodules for master branch
      run: git submodule update --init
    - name: Run Win-GenProjects.bat on master branch
      run: ./scripts/Win-GenProjects.bat
    