name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Chaekout master
      uses: actions/checkout@v2
    - name: Run Win-GenProjects.bat
      run: ./scripts/Win-GenProjects.bat
      working-directory: ./Hazel
    